// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace org.apache.arrow.flatbuf
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// ----------------------------------------------------------------------
/// A field represents a named column in a record / row batch or child of a
/// nested type.
public struct Field : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Field GetRootAsField(ByteBuffer _bb) { return GetRootAsField(_bb, new Field()); }
  public static Field GetRootAsField(ByteBuffer _bb, Field obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Field __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// Name is not required, in i.e. a List
  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  /// Whether or not this field can contain nulls. Should be true in general.
  public bool Nullable { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public org.apache.arrow.flatbuf.Type TypeType { get { int o = __p.__offset(8); return o != 0 ? (org.apache.arrow.flatbuf.Type)__p.bb.Get(o + __p.bb_pos) : org.apache.arrow.flatbuf.Type.NONE; } }
  /// This is the type of the decoded value if the field is dictionary encoded.
  public TTable? Type<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(10); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public org.apache.arrow.flatbuf.Null TypeAsNull() { return Type<org.apache.arrow.flatbuf.Null>().Value; }
  public org.apache.arrow.flatbuf.Int TypeAsInt() { return Type<org.apache.arrow.flatbuf.Int>().Value; }
  public org.apache.arrow.flatbuf.FloatingPoint TypeAsFloatingPoint() { return Type<org.apache.arrow.flatbuf.FloatingPoint>().Value; }
  public org.apache.arrow.flatbuf.Binary TypeAsBinary() { return Type<org.apache.arrow.flatbuf.Binary>().Value; }
  public org.apache.arrow.flatbuf.Utf8 TypeAsUtf8() { return Type<org.apache.arrow.flatbuf.Utf8>().Value; }
  public org.apache.arrow.flatbuf.Bool TypeAsBool() { return Type<org.apache.arrow.flatbuf.Bool>().Value; }
  public org.apache.arrow.flatbuf.Decimal TypeAsDecimal() { return Type<org.apache.arrow.flatbuf.Decimal>().Value; }
  public org.apache.arrow.flatbuf.Date TypeAsDate() { return Type<org.apache.arrow.flatbuf.Date>().Value; }
  public org.apache.arrow.flatbuf.Time TypeAsTime() { return Type<org.apache.arrow.flatbuf.Time>().Value; }
  public org.apache.arrow.flatbuf.Timestamp TypeAsTimestamp() { return Type<org.apache.arrow.flatbuf.Timestamp>().Value; }
  public org.apache.arrow.flatbuf.Interval TypeAsInterval() { return Type<org.apache.arrow.flatbuf.Interval>().Value; }
  public org.apache.arrow.flatbuf.List TypeAsList() { return Type<org.apache.arrow.flatbuf.List>().Value; }
  public org.apache.arrow.flatbuf.Struct_ TypeAsStruct_() { return Type<org.apache.arrow.flatbuf.Struct_>().Value; }
  public org.apache.arrow.flatbuf.Union TypeAsUnion() { return Type<org.apache.arrow.flatbuf.Union>().Value; }
  public org.apache.arrow.flatbuf.FixedSizeBinary TypeAsFixedSizeBinary() { return Type<org.apache.arrow.flatbuf.FixedSizeBinary>().Value; }
  public org.apache.arrow.flatbuf.FixedSizeList TypeAsFixedSizeList() { return Type<org.apache.arrow.flatbuf.FixedSizeList>().Value; }
  public org.apache.arrow.flatbuf.Map TypeAsMap() { return Type<org.apache.arrow.flatbuf.Map>().Value; }
  public org.apache.arrow.flatbuf.Duration TypeAsDuration() { return Type<org.apache.arrow.flatbuf.Duration>().Value; }
  public org.apache.arrow.flatbuf.LargeBinary TypeAsLargeBinary() { return Type<org.apache.arrow.flatbuf.LargeBinary>().Value; }
  public org.apache.arrow.flatbuf.LargeUtf8 TypeAsLargeUtf8() { return Type<org.apache.arrow.flatbuf.LargeUtf8>().Value; }
  public org.apache.arrow.flatbuf.LargeList TypeAsLargeList() { return Type<org.apache.arrow.flatbuf.LargeList>().Value; }
  public org.apache.arrow.flatbuf.RunEndEncoded TypeAsRunEndEncoded() { return Type<org.apache.arrow.flatbuf.RunEndEncoded>().Value; }
  public org.apache.arrow.flatbuf.BinaryView TypeAsBinaryView() { return Type<org.apache.arrow.flatbuf.BinaryView>().Value; }
  public org.apache.arrow.flatbuf.Utf8View TypeAsUtf8View() { return Type<org.apache.arrow.flatbuf.Utf8View>().Value; }
  public org.apache.arrow.flatbuf.ListView TypeAsListView() { return Type<org.apache.arrow.flatbuf.ListView>().Value; }
  public org.apache.arrow.flatbuf.LargeListView TypeAsLargeListView() { return Type<org.apache.arrow.flatbuf.LargeListView>().Value; }
  /// Present only if the field is dictionary encoded.
  public org.apache.arrow.flatbuf.DictionaryEncoding? Dictionary { get { int o = __p.__offset(12); return o != 0 ? (org.apache.arrow.flatbuf.DictionaryEncoding?)(new org.apache.arrow.flatbuf.DictionaryEncoding()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  /// children apply only to nested data types like Struct, List and Union. For
  /// primitive types children will have length 0.
  public org.apache.arrow.flatbuf.Field? Children(int j) { int o = __p.__offset(14); return o != 0 ? (org.apache.arrow.flatbuf.Field?)(new org.apache.arrow.flatbuf.Field()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChildrenLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// User-defined metadata
  public org.apache.arrow.flatbuf.KeyValue? CustomMetadata(int j) { int o = __p.__offset(16); return o != 0 ? (org.apache.arrow.flatbuf.KeyValue?)(new org.apache.arrow.flatbuf.KeyValue()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CustomMetadataLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<org.apache.arrow.flatbuf.Field> CreateField(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      bool nullable = false,
      org.apache.arrow.flatbuf.Type type_type = org.apache.arrow.flatbuf.Type.NONE,
      int typeOffset = 0,
      Offset<org.apache.arrow.flatbuf.DictionaryEncoding> dictionaryOffset = default(Offset<org.apache.arrow.flatbuf.DictionaryEncoding>),
      VectorOffset childrenOffset = default(VectorOffset),
      VectorOffset custom_metadataOffset = default(VectorOffset)) {
    builder.StartTable(7);
    Field.AddCustomMetadata(builder, custom_metadataOffset);
    Field.AddChildren(builder, childrenOffset);
    Field.AddDictionary(builder, dictionaryOffset);
    Field.AddType(builder, typeOffset);
    Field.AddName(builder, nameOffset);
    Field.AddTypeType(builder, type_type);
    Field.AddNullable(builder, nullable);
    return Field.EndField(builder);
  }

  public static void StartField(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddNullable(FlatBufferBuilder builder, bool nullable) { builder.AddBool(1, nullable, false); }
  public static void AddTypeType(FlatBufferBuilder builder, org.apache.arrow.flatbuf.Type typeType) { builder.AddByte(2, (byte)typeType, 0); }
  public static void AddType(FlatBufferBuilder builder, int typeOffset) { builder.AddOffset(3, typeOffset, 0); }
  public static void AddDictionary(FlatBufferBuilder builder, Offset<org.apache.arrow.flatbuf.DictionaryEncoding> dictionaryOffset) { builder.AddOffset(4, dictionaryOffset.Value, 0); }
  public static void AddChildren(FlatBufferBuilder builder, VectorOffset childrenOffset) { builder.AddOffset(5, childrenOffset.Value, 0); }
  public static VectorOffset CreateChildrenVector(FlatBufferBuilder builder, Offset<org.apache.arrow.flatbuf.Field>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, Offset<org.apache.arrow.flatbuf.Field>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<org.apache.arrow.flatbuf.Field>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<org.apache.arrow.flatbuf.Field>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChildrenVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddCustomMetadata(FlatBufferBuilder builder, VectorOffset customMetadataOffset) { builder.AddOffset(6, customMetadataOffset.Value, 0); }
  public static VectorOffset CreateCustomMetadataVector(FlatBufferBuilder builder, Offset<org.apache.arrow.flatbuf.KeyValue>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCustomMetadataVectorBlock(FlatBufferBuilder builder, Offset<org.apache.arrow.flatbuf.KeyValue>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCustomMetadataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<org.apache.arrow.flatbuf.KeyValue>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCustomMetadataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<org.apache.arrow.flatbuf.KeyValue>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCustomMetadataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<org.apache.arrow.flatbuf.Field> EndField(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<org.apache.arrow.flatbuf.Field>(o);
  }
}


static public class FieldVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyField(tablePos, 6 /*Nullable*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*TypeType*/, 1 /*org.apache.arrow.flatbuf.Type*/, 1, false)
      && verifier.VerifyUnion(tablePos, 8, 10 /*Type*/, org.apache.arrow.flatbuf.TypeVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 12 /*Dictionary*/, org.apache.arrow.flatbuf.DictionaryEncodingVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 14 /*Children*/, org.apache.arrow.flatbuf.FieldVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 16 /*CustomMetadata*/, org.apache.arrow.flatbuf.KeyValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
