// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace org.apache.arrow.flatbuf
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Interval : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Interval GetRootAsInterval(ByteBuffer _bb) { return GetRootAsInterval(_bb, new Interval()); }
  public static Interval GetRootAsInterval(ByteBuffer _bb, Interval obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Interval __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public org.apache.arrow.flatbuf.IntervalUnit Unit { get { int o = __p.__offset(4); return o != 0 ? (org.apache.arrow.flatbuf.IntervalUnit)__p.bb.GetShort(o + __p.bb_pos) : org.apache.arrow.flatbuf.IntervalUnit.YEAR_MONTH; } }

  public static Offset<org.apache.arrow.flatbuf.Interval> CreateInterval(FlatBufferBuilder builder,
      org.apache.arrow.flatbuf.IntervalUnit unit = org.apache.arrow.flatbuf.IntervalUnit.YEAR_MONTH) {
    builder.StartTable(1);
    Interval.AddUnit(builder, unit);
    return Interval.EndInterval(builder);
  }

  public static void StartInterval(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUnit(FlatBufferBuilder builder, org.apache.arrow.flatbuf.IntervalUnit unit) { builder.AddShort(0, (short)unit, 0); }
  public static Offset<org.apache.arrow.flatbuf.Interval> EndInterval(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<org.apache.arrow.flatbuf.Interval>(o);
  }
}


static public class IntervalVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unit*/, 2 /*org.apache.arrow.flatbuf.IntervalUnit*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
