name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
permissions:
  pages: write
  id-token: write
  pull-requests: write
jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            checkTarget: true
            docsTarget: true
            # Code coverage doesn't seem to work when PR's are opened from forked repositories, see discussion:
            #
            # >>> https://delta-users.slack.com/archives/C06P467JMBK/p1727730777683979?thread_ts=1727643486.229189&cid=C06P467JMBK
            #
            coverageTarget: false
            cloudTestTarget: true
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: false

      - name: Checkout specific delta-kernel-rs release
        shell: bash
        run: chmod -R +x .scripts/*.sh && .scripts/checkout-delta-kernel-rs.sh

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: |
            src/DeltaLake/Bridge
            src/DeltaLake/Kernel/delta-kernel-rs

      - name: Setup .NET
        uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
        with:
          dotnet-version: | 
            8.0.x
            9.0.x

      - name: Build
        # We intentionally just build debug mode in this CI. We build before
        # regen to confirm no interop header changes.
        run: dotnet build -c Release

      - name: Install LLVM and Clang
        if: ${{ matrix.checkTarget }}
        uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0 # v2.0.9
        with:
          version: "20.1.2"

      - name: Regen confirm unchanged
        if: ${{ matrix.checkTarget }}
        # Needs to be 16.0.0 until https://github.com/dotnet/ClangSharp/pull/506 released
        run: |
          dotnet tool install --global --version 20.1.2 ClangSharpPInvokeGenerator
          curl -L  https://www.nuget.org/api/v2/package/libclang.runtime.linux-x64/20.1.2 -o /tmp/libclang.zip
          curl -L https://www.nuget.org/api/v2/package/libClangSharp.runtime.linux-x64/20.1.2 -o /tmp/libclangsharp.zip
          unzip -od /tmp/libclang /tmp/libclang.zip
          unzip -od /tmp/libclangsharp /tmp/libclangsharp.zip
          cp /tmp/libclang/runtimes/linux-x64/native/libclang.so /home/runner/.dotnet/tools/.store/clangsharppinvokegenerator/20.1.2/clangsharppinvokegenerator/20.1.2/tools/net8.0/any/
          cp /tmp/libclangsharp/runtimes/linux-x64/native/libClangSharp.so /home/runner/.dotnet/tools/.store/clangsharppinvokegenerator/20.1.2/clangsharppinvokegenerator/20.1.2/tools/net8.0/any/
          # temporarily disable generation test
          # make generate-bindings
          npx doctoc README.md
          git config --global core.safecrlf false
          git diff --exit-code

      # dotnet format failing due to CRLF/LF issues
      # - name: Check format
      #   if: ${{ matrix.checkTarget }}
      #   run: dotnet format --verify-no-changes

      - name: Test
        env:
          RUST_BACKTRACE: 1
          # increased stack size currently necessary for osx
          DOTNET_DefaultStackSize: "180000"
        run: dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info --logger "console;verbosity=detailed" --blame-crash -v n

      - name: Upload test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: test-fail-${{ matrix.os }}
          path: tests/DeltaLake.Tests/TestResults

      - name: Setup LCOV
        if: github.event_name == 'pull_request' && matrix.coverageTarget
        uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470 # v1.1.0

      - name: Report code coverage
        if: github.event_name == 'pull_request' && matrix.coverageTarget
        uses: zgosalvez/github-actions-report-lcov@73c068acfc6a265af813132fbca7ef8738a1f52f # v3.1.8
        with:
          coverage-files: tests/DeltaLake.Tests/lcov.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #working-directory: apps/my-first-app
          update-comment: true

      - name: Build docs
        if: ${{ matrix.docsTarget }}
        run: |
          dotnet tool update -g docfx
          docfx src/DeltaLake.ApiDoc/docfx.json --warningsAsErrors

      - name: Upload artifact
        if: ${{ github.ref == 'refs/heads/main' && matrix.docsTarget }}
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          # Upload entire repository
          path: "src/DeltaLake.ApiDoc/_site"

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' && matrix.docsTarget }}
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
